highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://me.xuzhang.work/vitae
author: Xu Zhang

# edit this section with your information
# snakeshawn.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Xu Zhang's Resume
name: Xu Zhang
email: xzhcn6@gmail.com
email_full: mailto:xzhcn6@gmail.com
website: me.xuzhang.work
website_full: http://me.xuzhang.work
github: snakeshawn
twitter: Snake_Shawn
tel: +86 17600853112
tel_full: tel:+86 17600853112
google_maps: 'https://goo.gl/maps/tSuJfL5YZdo'
address: Internet Innovation Center, HaiDian District
postcode: 
city: Beijing
country: China
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
