highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://snakeshawn.github.io/vitae
author: Shawn Zhang

# edit this section with your information
# snakeshawn.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Shawn Zhang's Resume
name: Shawn Zhang
email: snakeshawnzhang</br>@gmail.com
email_full: mailto:snakeshawnzhang@gmail.com
website: snakeshawn.github.io
website_full: https://snakeshawn.github.io
github: snakeshawn
twitter: Snake_Shawn
tel: +852 5424 7356
tel_full: tel:+852 54247356
google_maps: 'https://goo.gl/maps/tSuJfL5YZdo'
address: AC3,City University of Hong Kong,Koowloon
postcode: 
city: Hong Kong
country: China
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
